# Generated by Django 2.0.6 on 2021-04-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='导航栏名')),
                ('nav_url', models.CharField(max_length=128, verbose_name='导航栏链接')),
                ('type', models.BooleanField(default=0, verbose_name='导航类型')),
                ('orders', models.IntegerField(default=1, verbose_name='排序')),
            ],
            options={
                'verbose_name': '导航栏',
                'verbose_name_plural': '导航栏',
                'db_table': 'laf_nav',
            },
        ),
    ]
