# Generated by Django 2.0.6 on 2021-04-14 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='图片地址')),
            ],
            options={
                'verbose_name': '物品图片',
                'verbose_name_plural': '物品图片',
                'db_table': 'laf_goodsImage',
            },
        ),
        migrations.CreateModel(
            name='GoodsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_lost', models.BooleanField(default=True, verbose_name='是否为失物')),
                ('name', models.CharField(max_length=16, verbose_name='物品名称')),
                ('the_type', models.SmallIntegerField(choices=[(0, '文件'), (1, '文具'), (2, '日常用品'), (3, '玩具'), (4, '电子产品'), (5, '衣服'), (6, '其他')], default=0, verbose_name='物品类型')),
                ('description', models.CharField(max_length=255, verbose_name='物品描述')),
                ('date', models.DateTimeField(verbose_name='时间(拾取/丢失)')),
                ('area', models.CharField(max_length=128, verbose_name='地点(拾取/丢失)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户编号')),
            ],
            options={
                'verbose_name': '物品信息',
                'verbose_name_plural': '物品信息',
                'db_table': 'laf_goods',
            },
        ),
        migrations.AddField(
            model_name='goodsimage',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsInfo', verbose_name='物品编号'),
        ),
    ]
