# Generated by Django 2.0.6 on 2021-04-14 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_goodsmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsinfo',
            name='status',
            field=models.BooleanField(default=True, verbose_name='是否有效'),
        ),
    ]
